// package fields provides default mappings for transmute and cqr fields.
package fields

var (
	Affiliation                  = "affiliation"
	AllFields                    = "all_fields"
	Author                       = "author"
	Authors                      = "authors"
	AuthorCorporate              = "author_corporate"
	AuthorFirst                  = "author_first"
	AuthorFull                   = "author_full"
	AuthorIdentifier             = "author_identifier"
	AuthorLast                   = "author_last"
	Book                         = "book"
	ConflictOfInterestStatements = "conflict_of_interest_statements"
	DateCompletion               = "date_completion"
	DateCreate                   = "date_create"
	DateEntrez                   = "date_entrez"
	DateMeSH                     = "date_mesh"
	DateModification             = "date_modification"
	DatePublication              = "date_publication"
	ECRNNumber                   = "ec_rn_number"
	Editor                       = "editor"
	Filter                       = "filter"
	GrantNumber                  = "grant_number"
	ISBN                         = "isbn"
	Investigator                 = "investigator"
	InvestigatorFull             = "investigator_full"
	Issue                        = "issue"
	Journal                      = "journal"
	Language                     = "language"
	LocationID                   = "location_id"
	MeSHMajorTopic               = "mesh_major_topic"
	MeSHSubheading               = "mesh_subheading"
	MeSHTerms                    = "mesh_terms"
	OtherTerm                    = "other_term"
	Pagination                   = "pagination"
	PharmacologicalAction        = "pharmacological_action"
	PublicationType              = "publication_type"
	Publisher                    = "publisher"
	SecondarySourceID            = "secondary_source_id"
	SubjectPersonalName          = "subject_personal_name"
	SupplementaryConcept         = "supplementary_concept"
	FloatingMeshHeadings         = "floating_mesh_headings"
	TextWord                     = "text_word"
	Title                        = "title"
	TitleAbstract                = "title_abstract"
	TransliteratedTitle          = "transliterated_title"
	Volume                       = "volume"
	Abstract                     = "text"
	MeshHeadings                 = "mesh_headings"
	MajorFocusMeshHeading        = "major_mesh_headings"
	PublicationDate              = "publication_date"
	PublicationStatus            = "publication_status"
	PMID                         = "pmid"
)
